name: deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: image-color-canvas-world
  IMAGE: gcr.io/${{ env.PROJECT_ID }}/sandbox:${{ github.sha }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        run: cargo build --release --all-features
      - name: GCP Authenticate
        uses: google-github-actions/setup-gcloud@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker
      - name: Build a docker image
        run: docker build . -t $IMAGE
      - name: Push the docker image
        run: docker push $IMAGE
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy sandbox \
            --image $IMAGE \
            --project $PROJECT_ID \
            --region us-central1 \
            --allow-unauthenticated \
            --platform managed
