name: deploy

on:
  push:
    branches:
      - main

env:
  IMAGE: gcr.io/image-color-canvas-world/main:${{ github.sha }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build
        run: cargo build --release --all-features
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: setup-gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker
      - name: Build a docker image
        run: docker build . -t $IMAGE
      - name: Push the docker image
        run: docker push $IMAGE
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy main \
            --image $IMAGE \
            --project image-color-canvas-world \
            --region us-central1 \
            --allow-unauthenticated \
            --platform managed
