name: build test

on: pull_request

jobs:
  test:
    name: build test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install npm dependencies (npm ci)
        run: npm ci
      - run: npm run build
      - run: npx tsc --project ./functions/tsconfig.json
