name: build test

on: pull_request

jobs:
  test:
    name: build test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno check ./main.tsx
